import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {dates,quote,conflict,authenticated} from '../netlify/functions/lib/bookings.mjs';
import {createHandler} from '../netlify/functions/bookings.mjs';
process.env.MBOA_ADMIN_SESSION_SECRET='booking-test-secret';
function memory(){const entries=new Map();let n=0;return {get:async k=>structuredClone(entries.get(k)?.data||null),getWithMetadata:async k=>structuredClone(entries.get(k)||null),setJSON:async(k,data,c={})=>{const old=entries.get(k);if(c.onlyIfNew&&old||c.onlyIfMatch&&old?.etag!==c.onlyIfMatch)return {modified:false};entries.set(k,{data:structuredClone(data),etag:String(++n)});return {modified:true};}};}
const vehicle={slug:'rav4-test',name:'RAV4',status:'disponible',price:5500000};
const future=n=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
function cookie(){const expires=String(Math.floor(Date.now()/1000)+300);return 'mboa_admin_session='+expires+'.'+crypto.createHmac('sha256',process.env.MBOA_ADMIN_SESSION_SECRET).update(expires).digest('hex');}
const request=(body,admin=false)=>new Request('https://mboaauto.com/.netlify/functions/bookings',{method:'POST',headers:{origin:'https://mboaauto.com','Content-Type':'application/json',...(admin?{cookie:cookie()}:{})},body:JSON.stringify({slug:vehicle.slug,...body})});
const form=()=>({action:'request',kind:'rental',start:future(3),end:future(5),name:'Test client',phone:'+237691650428',notes:''});
async function setup(){const store=memory(),handler=createHandler(()=>store,async()=>[vehicle]);const r=await handler(request({action:'config',config:{enabled:true,dailyRate:25000,fee:5000,depositPercent:30,seats:5}},true));assert.equal(r.status,200);return {store,handler};}
test('dates reject impossible dates, past periods and zero-day rentals; quote excludes return day',()=>{
 const now=new Date('2026-10-09T12:00:00Z');assert.equal(dates('2026-10-10','2026-10-12',now),2);assert.throws(()=>dates('2027-02-30','2027-03-05',now));assert.throws(()=>dates('2026-10-08','2026-10-10',now));assert.throws(()=>dates('2026-10-10','2026-10-10',now));assert.deepEqual(quote({dailyRate:25000,fee:5000,depositPercent:30},'2026-10-10','2026-10-12',now),{days:2,dailyRate:25000,fee:5000,total:55000,deposit:16500});
});
test('adjacent rentals are accepted, purchases block the vehicle',()=>{const b={id:'1',kind:'rental',status:'confirmed',start:'2026-11-01',end:'2026-11-03'};assert.equal(conflict([b],{kind:'rental',start:'2026-11-03',end:'2026-11-05'}),false);assert.equal(conflict([b],{kind:'rental',start:'2026-11-02',end:'2026-11-04'}),true);assert.equal(conflict([b],{kind:'purchase'}),true);});
test('admin authentication, origin and rate limits are enforced',async()=>{const {handler}=await setup();assert.ok(authenticated(new Request('https://mboaauto.com',{headers:{cookie:cookie()}})));assert.equal((await handler(new Request('https://mboaauto.com?admin=1'))).status,401);assert.equal((await handler(request({action:'config',config:{}}))).status,401);assert.equal((await handler(new Request('https://mboaauto.com',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'}))).status,403);for(let i=0;i<10;i++)assert.equal((await handler(request(form()))).status,201);assert.equal((await handler(request(form()))).status,429);});
test('server calculates price and anonymous availability contains no client data',async()=>{const {handler}=await setup();const r=await handler(request({...form(),total:1})),d=await r.json();assert.equal(r.status,201);assert.equal(d.booking.total,55000);assert.equal(d.booking.deposit,16500);const availability=await (await handler(new Request('https://mboaauto.com'))).json();assert.ok(!JSON.stringify(availability).includes('Test client'));assert.ok(!JSON.stringify(availability).includes('691650428'));assert.ok(!JSON.stringify(availability).includes(d.token));assert.equal((await handler(request({action:'track',token:'a'.repeat(64)}))).status,404);const track=await (await handler(request({action:'track',token:d.token}))).json();assert.equal(track.booking.id,d.booking.id);assert.ok(!('phone' in track.booking));});
test('simultaneous confirmations of overlapping requests cannot both succeed',async()=>{const {handler,store}=await setup();const a=await (await handler(request(form()))).json(),b=await (await handler(request(form()))).json();const update=d=>request({action:'update',id:d.booking.id,revision:d.booking.revision,status:'confirmed',paid:0,paymentMethod:'none'},true);const responses=await Promise.all([handler(update(a)),handler(update(b))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const ledger=await store.get('vehicle/'+vehicle.slug);assert.equal(ledger.bookings.filter(b=>b.status==='confirmed').length,1);assert.equal((await handler(request(form()))).status,409);});
test('client can cancel pending requests only; stale revisions cannot overwrite payment',async()=>{const {handler}=await setup();const a=await (await handler(request(form()))).json();assert.equal((await handler(request({action:'cancel',token:a.token}))).status,200);assert.equal((await handler(request({action:'update',id:a.booking.id,revision:a.booking.revision,status:'confirmed',paid:0,paymentMethod:'none'},true))).status,409);const b=await (await handler(request(form()))).json();const updated=await handler(request({action:'update',id:b.booking.id,revision:b.booking.revision,status:'confirmed',paid:16500,paymentMethod:'mobile-money'},true));assert.equal(updated.status,200);assert.equal((await handler(request({action:'cancel',token:b.token}))).status,409);assert.equal((await handler(request({action:'update',id:b.booking.id,revision:b.booking.revision,status:'confirmed',paid:0,paymentMethod:'none'},true))).status,409);});

test('retrying the same request after a lost response does not create a duplicate',async()=>{const {handler,store}=await setup(),body={...form(),requestKey:'b'.repeat(64)};const first=await (await handler(request(body))).json(),second=await (await handler(request(body))).json();assert.equal(first.booking.id,second.booking.id);assert.equal((await store.get('vehicle/'+vehicle.slug)).bookings.length,1);});
