import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { processOne, encrypt, decrypt, authenticated, postFor, validateKey } from '../netlify/functions/lib/google-sync.mjs';
import { createHandler } from '../netlify/functions/admin-google-sync.mjs';
process.env.MBOA_ADMIN_SESSION_SECRET='test-only-secret';
process.env.MBOA_GITHUB_TOKEN='test-token';
const vehicle={slug:'rav4-test',name:'Toyota RAV4',year:2008,fuel:'Essence',type:'SUV',price:5500000,location:'Yaoundé',cover:'01.jpg',status:'disponible',google_sync_requested:true};
function memory(){const entries=new Map();let revision=0;return {entries,get:async k=>entries.get(k)?.data||null,getWithMetadata:async k=>entries.get(k)||null,setJSON:async(k,data,conditions={})=>{const old=entries.get(k);if(conditions.onlyIfNew&&old||conditions.onlyIfMatch&&old?.etag!==conditions.onlyIfMatch)return {modified:false};const etag=String(++revision);entries.set(k,{data:structuredClone(data),etag});return {modified:true,etag};}};}
async function setup(){const store=memory();await store.setJSON('config',{enabled:true,encryptedKey:encrypt('test-key')});return store;}
function transport({live=true,fail=false,refuse=false}={}){let posts=0;const fetcher=async(url,opts={})=>{url=String(url);if(url.includes('api.github.com'))return Response.json({content:Buffer.from(JSON.stringify([vehicle])).toString('base64')});if(url.endsWith('vehicules.json'))return Response.json(live?[vehicle]:[]);if(opts.method==='HEAD')return new Response(null,{status:200,headers:{'Content-Type':url.endsWith('.jpg')?'image/jpeg':'text/html'}});if(opts.method==='POST'){posts++;assert.equal(JSON.parse(opts.body).params.cta_url,'https://mboaauto.com/vehicules/rav4-test.html');if(fail)throw Error('Unknown outcome');return Response.json(refuse?{error:'Denied'}:{result:'Post created'}, {status:refuse?403:200});}throw Error('Unexpected request');};return {fetcher,count:()=>posts};}
test('encrypts keys and rejects tampering',()=>{const e=encrypt('secret-api-key');assert.equal(decrypt(e),'secret-api-key');assert.ok(!JSON.stringify(e).includes('secret-api-key'));e.tag=Buffer.alloc(16).toString('base64');assert.throws(()=>decrypt(e));});
test('concurrent workers publish each vehicle once',async()=>{const store=await setup(),t=transport();await Promise.all([processOne(store,t.fetcher),processOne(store,t.fetcher)]);assert.equal(t.count(),1);assert.equal((await store.get('vehicle/rav4-test')).status,'sent');await processOne(store,t.fetcher);assert.equal(t.count(),1);});
test('waits for deployment and excludes historical stock',async()=>{const store=await setup(),t=transport({live:false});assert.equal((await processOne(store,t.fetcher)).status,'waiting');assert.equal(t.count(),0);vehicle.google_sync_requested=false;try{assert.equal((await processOne(store,transport().fetcher)).status,'idle');}finally{vehicle.google_sync_requested=true;}});
test('timeout never causes automatic duplicate retry',async()=>{const store=await setup(),t=transport({fail:true});assert.equal((await processOne(store,t.fetcher)).status,'needs_review');await processOne(store,t.fetcher);assert.equal(t.count(),1);});
test('refusal remains visible, sold vehicles are skipped',async()=>{const store=await setup(),t=transport({refuse:true});assert.equal((await processOne(store,t.fetcher)).status,'error');vehicle.status='vendu';try{assert.equal((await processOne(await setup(),transport().fetcher)).status,'idle');}finally{vehicle.status='disponible';}});
test('admin endpoints reject anonymous and cross-origin configuration',async()=>{const handler=createHandler(memory);assert.equal((await handler(new Request('https://mboaauto.com/.netlify/functions/admin-google-sync'))).status,401);const expires=String(Math.floor(Date.now()/1000)+60),sig=crypto.createHmac('sha256',process.env.MBOA_ADMIN_SESSION_SECRET).update(expires).digest('hex');const cookie=`mboa_admin_session=${expires}.${sig}`;assert.ok(authenticated(new Request('https://mboaauto.com',{headers:{cookie}})));assert.equal((await handler(new Request('https://mboaauto.com',{method:'POST',headers:{cookie,origin:'https://evil.example'},body:'{}'}))).status,403);});
test('key connection validates target location and write capability',async()=>{let i=0;await validateKey('key',async()=>Response.json(i++===0?[{id:'create_local_post'}]:{data:[{location_id:'locations/4649832843426570918'}]}));await assert.rejects(validateKey('key',async()=>Response.json([])));});
test('post contains only vehicle data and public canonical link',()=>{const p=postFor(vehicle);assert.ok(p.summary.includes('5'));assert.equal(p.language_code,'fr');assert.throws(()=>postFor({...vehicle,cover:'../../secret.jpg'}));});
