import React from 'react';
import { Image, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { photoUrl, Vehicle } from '../lib/catalog';
import { useCatalog } from '../lib/store';
export const colors = { ink: '#10202a', red: '#e91e36', green: '#14734a', muted: '#63717c', line: '#e4e9eb', bg: '#f7f8f9' };
export async function openUrl(url: string, onError: (s: string) => void) { try { await Linking.openURL(url); } catch { onError('Impossible d’ouvrir ce lien sur cet appareil.'); } }
export function Brand() { return <View><Text style={s.brand}>MBOA <Text style={{ color: colors.red }}>AUTO</Text></Text><Text style={s.tagline}>VOTRE PROCHAIN VÉHICULE</Text></View>; }
export function Button({ title, onPress, secondary = false, disabled = false }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, pressed && { opacity: .7 }, disabled && { opacity: .5 }]}><Text style={[s.buttonText, secondary && { color: colors.ink }]}>{title}</Text></Pressable>; }
export function Favorite({ vehicle }: { vehicle: Vehicle }) { const { favorites, toggle, ready } = useCatalog(); const active = favorites.includes(vehicle.slug); return <Pressable disabled={!ready} accessibilityRole="button" accessibilityLabel={(active ? 'Retirer des favoris : ' : 'Ajouter aux favoris : ') + vehicle.name} accessibilityState={{ selected: active }} onPress={() => toggle(vehicle.slug)} style={s.favorite}><Text style={{ fontSize: 27, color: active ? colors.red : colors.ink }}>{active ? '♥' : '♡'}</Text></Pressable>; }
export function VehicleCard({ vehicle }: { vehicle: Vehicle }) { const [failed, setFailed] = React.useState(false); const v = vehicle; return <View style={s.card}><Pressable accessibilityRole="button" accessibilityLabel={'Voir ' + v.name} onPress={() => router.push({ pathname: '/vehicule/[slug]', params: { slug: v.slug } })}><View style={s.picture}>{failed ? <Text style={s.placeholder}>Photo indisponible</Text> : <Image source={{ uri: photoUrl(v) }} onError={() => setFailed(true)} style={s.image} resizeMode="cover" />}<View style={s.type}><Text style={s.typeText}>{v.status === 'disponible' ? v.type : v.status === 'reserve' ? 'Réservé' : 'Indisponible'}</Text></View></View><View style={s.cardBody}><Text style={s.brandLine}>{v.brand.toUpperCase()} · {v.year || 'Année non précisée'}</Text><Text style={s.title}>{v.name}</Text><Text style={s.price}>{v.price_display}</Text><Text style={s.meta}>{v.fuel} · {v.location}</Text><Text numberOfLines={2} style={s.specs}>{v.specs}</Text><Text style={s.detail}>Découvrir le véhicule →</Text></View></Pressable><View style={s.favoritePosition}><Favorite vehicle={v} /></View></View>; }
export function Notice() { const { error, storageError, stale, updated } = useCatalog(); if (!error && !storageError && !stale) return null; return <View style={s.notice}><Text style={s.noticeText}>{error || 'Catalogue enregistré sur cet appareil. Actualisation en cours.'}{updated && stale ? '\nDernière mise à jour : ' + new Date(updated).toLocaleDateString('fr-FR') : ''}{storageError ? '\n' + storageError : ''}</Text></View>; }
export const s = StyleSheet.create({ brand: { fontSize: 24, fontWeight: '900', letterSpacing: -.8, color: colors.ink }, tagline: { fontSize: 8, letterSpacing: 1.3, color: colors.muted, marginTop: 3 }, button: { minHeight: 48, borderRadius: 12, backgroundColor: colors.red, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 12 }, secondary: { backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line }, buttonText: { color: '#fff', fontSize: 15, fontWeight: '700' }, card: { backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, borderRadius: 20, overflow: 'hidden', marginBottom: 18 }, picture: { height: 215, backgroundColor: '#e8edef' }, image: { width: '100%', height: '100%' }, placeholder: { textAlign: 'center', paddingTop: 90, color: colors.muted }, type: { position: 'absolute', left: 14, bottom: 14, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#fff' }, typeText: { fontSize: 12, fontWeight: '700', color: colors.ink }, cardBody: { padding: 18 }, brandLine: { color: colors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1 }, title: { fontSize: 20, fontWeight: '800', color: colors.ink, marginTop: 7 }, price: { color: colors.red, fontSize: 21, fontWeight: '800', marginTop: 10 }, meta: { color: colors.muted, fontSize: 13, marginTop: 10 }, specs: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 9 }, detail: { color: colors.ink, fontWeight: '700', fontSize: 13, marginTop: 15 }, favorite: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line }, favoritePosition: { position: 'absolute', right: 12, top: 12 }, notice: { padding: 14, borderRadius: 12, backgroundColor: '#fff2df', marginBottom: 15 }, noticeText: { fontSize: 13, lineHeight: 20, color: '#755224' } });
