(() => {
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>Number(n).toLocaleString('fr-FR')+' FCFA';
 const labels={pending:'À confirmer',confirmed:'Confirmée',completed:'Terminée',cancelled:'Annulée'};
 let vehicles=[],editing=null,saving=false;
 async function api(body){const r=await fetch('/.netlify/functions/bookings?admin=1',{method:body?'POST':'GET',cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(r.status===401){location.href='/admin/';throw Error('Connexion expirée.');}const d=await r.json();if(!r.ok)throw Error(d.error||'Service indisponible.');return d;}
 function notice(s,error=false){$('notice').textContent=s;$('notice').className='notice'+(error?' error':'');}
 function all(){return vehicles.flatMap(v=>v.bookings.map(b=>({...b,slug:v.slug,vehicle:v.name})));}
 function fillConfig(){const c=vehicles.find(v=>v.slug===$('configVehicle').value)?.config||{};$('rentalEnabled').value=String(Boolean(c.enabled));for(const id of ['dailyRate','fee','depositPercent','seats'])$(id).value=c[id]||0;}
 function render(){const rows=all(),slug=$('vehicleFilter').value,status=$('statusFilter').value;
  $('pendingCount').textContent=rows.filter(b=>b.status==='pending').length;$('confirmedCount').textContent=rows.filter(b=>b.status==='confirmed').length;$('paidTotal').textContent=rows.reduce((n,b)=>n+b.paid,0).toLocaleString('fr-FR');
  const blocks=rows.filter(b=>(!slug||b.slug===slug)&&['confirmed','completed'].includes(b.status)&&(b.kind==='purchase'||b.end>=new Date(Date.now()+3600000).toISOString().slice(0,10)));
  $('planning').textContent=blocks.length?'Véhicules bloqués : '+blocks.map(b=>b.vehicle+(b.kind==='rental'?' · '+b.start+' → '+b.end:' · réservation à l’achat')).join(' ; '):'Aucune période ni réservation à l’achat confirmée dans cette sélection.';
  $('bookings').innerHTML=rows.filter(b=>(!slug||b.slug===slug)&&(!status||b.status===status)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(b=>{
   const digits=b.phone.replace(/\D/g,''),phone=digits.length===9?'237'+digits:digits;
   return '<article class="card"><div class="client-top"><h2>'+esc(b.vehicle)+'</h2><span class="badge">'+labels[b.status]+'</span></div><p>'+esc(b.name)+' · '+esc(b.phone)+'</p><p>'+esc(b.kind==='rental'?'Location · '+b.start+' → '+b.end+' · '+b.days+' jour(s)':'Réservation à l’achat')+'</p><p>Total : '+cash(b.total)+' · Acompte prévu : '+cash(b.deposit)+'<br>Reçu : '+cash(b.paid)+' · Solde : '+cash(b.total-b.paid)+'</p><p class="details">'+esc(b.notes)+'</p><small>Référence : '+esc(b.id.slice(0,8))+' · '+new Date(b.createdAt).toLocaleString('fr-FR')+'</small><div class="actions"><button data-edit="'+b.id+'">Traiter</button><a class="btn" href="https://wa.me/'+esc(phone)+'?text='+encodeURIComponent('Bonjour '+b.name+', ici Arthur de Mboa Auto. Je vous contacte au sujet de votre demande '+b.id.slice(0,8)+' pour '+b.vehicle+'.')+'" target="_blank" rel="noopener">Contacter sur WhatsApp</a></div></article>';
  }).join('')||'<p>Aucune demande dans cette sélection.</p>';
 }
 async function load(){const chosen=$('configVehicle').value,filter=$('vehicleFilter').value;vehicles=(await api()).vehicles;$('configVehicle').innerHTML=vehicles.map(v=>'<option value="'+esc(v.slug)+'">'+esc(v.name)+'</option>').join('');$('vehicleFilter').innerHTML='<option value="">Tous</option>'+$('configVehicle').innerHTML;if(chosen)$('configVehicle').value=chosen;$('vehicleFilter').value=filter;fillConfig();render();}
 $('refresh').onclick=async()=>{try{await load();notice('Suivi actualisé.');}catch(e){notice(e.message,true);}};
 $('configVehicle').onchange=fillConfig;$('vehicleFilter').onchange=$('statusFilter').onchange=render;
 $('configForm').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;$('saveConfig').disabled=true;try{await api({action:'config',slug:$('configVehicle').value,config:{enabled:$('rentalEnabled').value==='true',...Object.fromEntries(['dailyRate','fee','depositPercent','seats'].map(id=>[id,Number($(id).value)]))}});await load();notice('Tarifs enregistrés.');}catch(err){notice(err.message,true);}finally{saving=false;$('saveConfig').disabled=false;}};
 $('bookings').onclick=e=>{const b=e.target.closest('[data-edit]');if(!b)return;editing=all().find(x=>x.id===b.dataset.edit);$('bookingDetails').textContent=editing.name+' · '+editing.vehicle+' · Total : '+cash(editing.total);$('bookingStatus').value=editing.status;$('bookingPaid').value=editing.paid;$('bookingPaid').max=editing.total;$('paymentMethod').value=editing.paymentMethod;$('editNotice').textContent='';$('editor').showModal();};
 $('closeEditor').onclick=()=>{if(!saving)$('editor').close();};$('editor').addEventListener('cancel',e=>{if(saving)e.preventDefault();});
 $('bookingEditor').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;$('saveBooking').disabled=true;try{await api({action:'update',slug:editing.slug,id:editing.id,revision:editing.revision,status:$('bookingStatus').value,paid:Number($('bookingPaid').value),paymentMethod:$('paymentMethod').value});$('editor').close();await load();notice('Demande mise à jour. Informez le client des conditions confirmées.');}catch(err){$('editNotice').textContent=err.message;}finally{saving=false;$('saveBooking').disabled=false;}};
 $('exportBookings').onclick=()=>{const cell=s=>'"'+String(s??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const fields=['id','vehicle','name','phone','kind','start','end','status','total','paid','paymentMethod'];const content='\ufeff'+[fields,...all().map(b=>fields.map(f=>b[f]))].map(row=>row.map(cell).join(';')).join('\r\n');const u=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='mboa-reservations.csv';a.click();URL.revokeObjectURL(u);};
 load().then(()=>{$('loading').hidden=true;document.body.setAttribute('aria-busy','false');}).catch(e=>{$('loading').textContent=e.message;});
})();
